apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: webapps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: saidiwissem/app:latest  # Use the latest Docker image
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: webapps
spec:
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 8080  # The service port
      targetPort: 8080  # The container port
  type: NodePort  # Change to LoadBalancer if you need an external IP
