apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: webapps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app-container
        image: saidiwissem/app:latest  # Use the latest Docker image
        ports:
        - containerPort: 8080
        - containerPort: 8443
        - containerPort: 9990
        # Optional: Add health checks for better reliability
        readinessProbe:
          httpGet:
            path: /health  # Change this to the appropriate health check endpoint
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health  # Change this to the appropriate health check endpoint
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: webapps
spec:
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 8080  # The service port
      targetPort: 8080  # The container port
      # Optional: Specify a NodePort if needed
      nodePort: 30000  # Choose a port within the NodePort range or omit this line to let Kubernetes allocate one
  type: NodePort  # Change to LoadBalancer if you need an external IP
